/* AUTOGENERATED BY gen_version.py! */
#ifndef __VERSION_H
#define __VERSION_H

char * catk_boot_banner = "Meow! CatK kernel version %s (%s) compiled by sushi@DESKTOP-FAAPLOO using %s on %s\n";

#endif /* __VERSION_H */
