#include <iostream>
#include <cstring>
#include <fstream>
#include <vector>
#include <sys/stat.h>
#include <parser.hpp>

bool nasm_file = false;

static void show_usage(void)
{
    std::cout << "usage: gen_config {config file}\n";
    std::cout << "example:\n\tgen_config kernel.config\n";
}

static bool file_exists(const char * path)
{
    struct stat buf;
    return stat(path, &buf);
}

int parser::parse_config_line(const char * line, std::vector<struct cfg_option>&list)
{
    if(strncmp(line, "CATK", 4))
    {
        return 0;
    }
    int index = strcspn(line, "=");
    /* now i know what you're thinking.. */

    /* 
     * "YOU CANT DO ADDITION ON A STRING, ITS NOT GONNA COMPILE!"
     *  ^
     *  This is true (except for the part that says it wont compile), but what I'm
     *  actually doing is skipping 'index' amount of characters in the string.
    */
    std::string name(strtok((char *)line, "="));
    line += index + 1;
    std::string value(line);
    list.push_back({.name = name, .value = value});
    return 0;
}

bool parser::is_bool(std::string&str)
{
    return (strlen(str.data()) < 2);
}

int main(int argc, char * argv[])
{
    if(argc < 2)
    {
        show_usage();
        return 1;
    }

    if(argv[2] && !strcmp(argv[2], "-n"))
        nasm_file = true;

    if(file_exists(argv[1]))
    {
        std::cerr << "failed to open file.\n";
        return 1;
    }
    std::ifstream fptr(argv[1]);
    std::vector<struct cfg_option> options;
    std::string line;
    while(getline(fptr, line))
    {
        /* line.data() converts a 'std::string' to a 'char *' */
        if (parser::parse_config_line(line.data(), options))
        {
            fptr.close();
            return 1;
        }
    }
    if(!nasm_file)
    {
        std::cout << "#ifndef __CONFIG_H\n#define __CONFIG_H\n\n";
        std::cout << "/* autogenerated by gen_config */\n\n";
        for(int i = 0; i < options.size(); i++)
        {
            std::cout << "#define " << options.at(i).name;
            if(parser::is_bool(options.at(i).value))
            {
                char ch = options.at(i).value[0];
                char outch = (ch == 'y') ? '1' : '0';
                std::cout << " " << outch << "\n";
            }
            else
            {
                std::cout << " " << options.at(i).value << std::endl;
            }
        }
        std::cout << "#endif" << std::endl;
    }
    else
    {
        for(int i = 0; i < options.size(); i++)
        {
            std::cout << "%" << "define " << options.at(i).name;
            if(parser::is_bool(options.at(i).value))
            {
                char ch = options.at(i).value[0];
                char outch = (ch == 'y') ? '1' : '0';
                std::cout << " " << outch << "\n";
            }
            else
            {
                std::cout << " " << options.at(i).value << std::endl;
            }
        }
    }
    fptr.close();
    return 0;
}
