#!/bin/sh

set -e

TMP1=$(mktemp)
TMP2=$(mktemp)
TMP3=$(mktemp)

if [ -z "$OBJDUMP" ]; then
  OBJDUMP=objdump
fi

${OBJDUMP} -t $1 | sed '/\bd\b/d' | sort > "$TMP1"
grep "\.text" < "$TMP1" | cut -d' ' -f1 > "$TMP2"
grep "\.text" < "$TMP1" | awk 'NF{ print $NF }' > "$TMP3"

cat <<EOF >$2
// autogenerated by gen_syms.sh

#include <catk/trace.h>
#include <catk/compiler.h>

struct kern_syms _weak_ symlist[] = {
EOF

paste -d'$' "$TMP2" "$TMP3" | sed 's/^/    {0x/g' | sed 's/\$/, "/g' | sed 's/$/"},/g' >> $2

cat <<EOF >> $2
    {0xffffffff, "(unknown)"}
};
EOF

rm "$TMP1" "$TMP2" "$TMP3"
