#include <iostream>
#include <cstring>
#include <fstream>
#include <vector>
#include <cstdio>
#include <sys/stat.h>
#include <parser.hpp>

#define CATK_GEN_CONFIG 1

bool nasm_file = false;

void show_usage(void)
{
    std::cout << "usage: gen_config {config file}\n";
    std::cout << "example:\n\tgen_config kernel.config\n";
}

bool file_exists(const char * path)
{
    struct stat buf;
    return stat(path, &buf);
}

int parser::parse_config_line(const char * line, std::vector<struct cfg_option>&list)
{
#ifdef CATK_GEN_CONFIG
    if(strncmp(line, "CATK", 4))
    {
        return 0;
    }
#else
    if(strncmp(line, "CONFIG", 4))
    {
        return 0;
    }
#endif
    int index = strcspn(line, "=");
    /* now i know what you're thinking.. */

    /* 
     * "YOU CANT DO ADDITION ON A STRING, ITS NOT GONNA COMPILE!"
     *  ^
     *  This is true (except for the part that says it wont compile), but what I'm
     *  actually doing is skipping 'index' amount of characters in the string.
    */
    std::string name(strtok((char *)line, "="));
    line += index + 1;
    std::string value(line);
    struct cfg_option cfg = {
        .name = name,
        .value = value
    };
    list.push_back(cfg);
    return 0;
}

bool parser::is_bool(std::string&str)
{
    return (strlen(str.data()) < 2);
}

int main(int argc, char * argv[])
{
    if(argc < 2)
    {
        show_usage();
        return 1;
    }

    if(argv[2] && !strcmp(argv[2], "-n")) {
        nasm_file = true;
    }

    if(file_exists(argv[1]))
    {
        std::cerr << "failed to open file.\n";
        return 1;
    }

    std::ifstream fptr(argv[1]);
    std::vector<struct cfg_option> options;
    std::string line;
    while(getline(fptr, line))
    {
        /* line.data() converts a 'std::string' to a 'char *' */
        if (parser::parse_config_line(line.data(), options))
        {
            fptr.close();
            return 1;
        }
    }
    if(!nasm_file)
    {
        std::cout << "#ifndef __CONFIG_H\n#define __CONFIG_H\n\n";
        std::cout << "/* autogenerated by gen_config */\n\n";
        for(int i = 0; i < options.size(); i++)
        {
            if(parser::is_bool(options.at(i).value))
            {
                std::string value = options.at(i).value;
                if(strcmp(value.c_str(), "y") == 0)
                {
                    std::cout << "#define " << options.at(i).name << " 1\n";
                }
                else
                {
                    /* i hate using nested if statements but it is needed here */
                    if(strcmp(value.c_str(), "n") == 0)
                    {
                        /* skip */
                        continue;
                    }
                    else
                    {
                        std::cout << "#define " << options.at(i).name << " " << value << std::endl;
                    }
                }
            }
            else
            {
                std::cout << "#define " << options.at(i).name << " " << options.at(i).value << std::endl;
            }
        }
        std::cout << "\n#endif\n";
    }
    else /* support for NASM files */
    {
        for(int i = 0; i < options.size(); i++)
        {
            std::cout << "%" << "define " << options.at(i).name;
            if(parser::is_bool(options.at(i).value))
            {
                char ch = options.at(i).value[0];
                char outch = (ch == 'y') ? '1' : '0';
                std::cout << " " << outch << "\n";
            }
            else
            {
                std::cout << " " << options.at(i).value << std::endl;
            }
        }
        std::cout << std::endl;
    }
    fptr.close();
    return 0;
}
