#ifndef __CONFIG_H
#define __CONFIG_H

/* autogenerated by gen_config */

#define CATK_64BIT 0
#define CATK_APIC 0
#define CATK_MMU 0
#define CATK_LOGO 1
#define CATK_ACPI_EXPERIMENTAL 1
#define CATK_MOUNT_RETRIES 2
#define CATK_EXT2 1
#define CATK_FAT32 0
#define CATK_DEVFS 1
#define CATK_DEVFS_INODES_MAX 128
#define CATK_VIDEO_GENERIC 0
#define CATK_HEAP_FOREIGN 1
#define CATK_FORCE_VERBOSE 0
#define CATK_DEBUG_SERIAL 1
#define CATK_STACK_TRACE 1
#define CATK_SYSCALL_TRACE 1
#endif
