#ifndef __CONFIG_H
#define __CONFIG_H

/* autogenerated by gen_config */

#define CATK_ARCH_X86 1
#define CATK_MOUNT_RETRIES 2
#define CATK_EXT2 1
#define CATK_DEVFS 1
#define CATK_DEVFS_INODES_MAX 128
#define CATK_VIDEO_GENERIC 0
#define CATK_STACK_TRACE 1
#define CATK_SYSCALL_TRACE 1
#endif
